version: "3.9"
services:
  yoo-mysql:
    image: "mysql:8.0"
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
    command: [ '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci' ]

  yoo-nginx:
    image: "nginx:latest"
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./www/:/usr/share/nginx/www/
    depends_on:
      - yoo-mysql

  yoo-resource:
    image: "phostann/yoo-resource:latest"
    restart: unless-stopped
    volumes:
      - ./configs/:/app/configs/
      - ./assets/:/opt/assets
    depends_on:
      - yoo-mysql