// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectM = "projects"

// ProjectM mapped from table <projects>
type ProjectM struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int32     `gorm:"column:user_id;not null" json:"user_id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	SSHURL      string    `gorm:"column:ssh_url" json:"ssh_url"`        // ssh 地址
	HTTPURL     string    `gorm:"column:http_url" json:"http_url"`      // http 地址
	WebURL      string    `gorm:"column:web_url" json:"web_url"`        // 仓库主页
	BuildCmd    string    `gorm:"column:build_cmd" json:"build_cmd"`    // 构建命令
	Dist        string    `gorm:"column:dist;default:dist" json:"dist"` // 打包产物对应的文件夹， 默认为 dist
	Description string    `gorm:"column:description;not null" json:"description"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName ProjectM's table name
func (*ProjectM) TableName() string {
	return TableNameProjectM
}
